version: '3.7'
services:
    mysql:
      image: mysql:latest
      container_name: mysql
      restart: always
      environment:
        - 'MYSQL_ROOT_PASSWORD=root1234'
        - 'MYSQL_DATABASE=mysqlDb'
        - 'MYSQL_USER=mysql'
        - 'MYSQL_PASSWORD=1234'
      ports:
        - "3306:3306"
      volumes:
        - './mysql:/var/lib/mysql' 

    tomcatAssign:
      image: tomcat
      restart: always
      container_name: tomcatAssign
      ports:
        - "8083:8080"

    springbootassign:
            build: 
                  context: ./backend-assingment
                  dockerfile: Dockerfile
            container_name: springbootassign
            ports:
              - '8084:8080'
              - '8005:8005  '
            depends_on:
                  - tomcatAssign
                  - mysql
            environment:
                  - TOMCAT_URL=http://tomcatAssign:8083
            volumes:
                  - ./application/logs:/app/logs    